version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "3000:3000"  # Application port
      - "35729:35729"  # LiveReload port
    volumes:
      - ./src:/app/src
      - ./target:/app/target

