version: "3.8"
services:

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8081:8080
