version: '3.8'

services:
  spring-app:
    build:
      context: ./srcs/springboot/
    ports:
      - "3000:3000" # Application port
      - "35729:35729" # LiveReload port
    volumes:
      - ./srcs/springboot/src:/app/src
      - ./srcs/springboot/target:/app/target
    networks:
      - Springboot-angular
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - Springboot-angular

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - "8080:8080"
    networks:
      - Springboot-angular

  front:
    tty: true
    build:
      context: ./srcs/angular/
    ports:
      - '4200:4200'
    container_name: angular
    volumes:
      - "./srcs/angular/angular-app:/usr/src/app"
    restart: always
    networks:
      - Springboot-angular

networks:
  Springboot-angular:
