version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "3000:3000"  # Application port
      - "35729:35729"  # LiveReload port
    volumes:
      - ./src:/app/src
      - ./target:/app/target

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - "8080:8080"
    networks:
      - Springboot-angular

  front:
    tty: true
    build:
      context: ./front/
    ports:
      - '4200:4200'
    container_name: front
    volumes:
      - "./front/angular-app:/usr/src/app"
    restart: always
    networks:
      - Springboot-angular

networks:
  Springboot-angular:
