version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "3000:3000"  # Application port
      - "35729:35729"  # LiveReload port
    volumes:
      - ./src:/app/src
      - ./target:/app/target
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - "8080:8080"
