#version: '3.8'
#
#services:
#  spring:
#    image: dinokeke/spring-docker:0.0.2
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./target/classes:/workspace/BOOT-INF/classes/

version: '3'
services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
